package ai.engineering;

public enum MLCanvasType{
    PREDICTION_TASK,
    IMPACT_SIMULATION,
    DECISION,
    MAKING_PREDICTION,
    VALUE_PROPOSITION,
    DATA_COLLECTION,
    BUILDING_MODELS,
    DATA_SOURCES,
    FEATURES,
    LIVE_MONITORING,
    UNIDENTIFIED
}